/* Copyright PIER CALDERAN
   Licensed under the MIT License. */

// This file defines the mapping from the MT3620 reference development board (RDB) to the
// 'sample hardware' abstraction used by the samples at https://github.com/Azure/azure-sphere-samples.
// Some peripherals are on-board on the RDB, while other peripherals must be attached externally if needed.
// See TODO(85663) for more information on how to use hardware abstractions
// to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../sample_hardware.json.  Do not edit it directly.

#pragma once
#include "mt3620.h"

// ISU0 I2C, pin 20 (SDA) pin 19 (SCL) MPU6850
#define SAMPLE_ISU0_I2C MT3620_ISU0_I2C

// ISU1 I2C, pin 24 (SDA) pin 23 (SCL)
#define SAMPLE_ISU1_I2C MT3620_ISU1_I2C

// ISU2 I2C, pin 28 (SDA) pin 27 (SCL)
#define SAMPLE_ISU2_I2C MT3620_ISU2_I2C

// ISU1 SPI, pin 22 23 24 25 26
#define SAMPLE_ISU1_SPI MT3620_ISU1_SPI
#define SAMPLE_ARDUINO_I2C MT3620_ISU1_I2C
// MT3620 PIN5 DHT
#define SENS_DHT MT3620_GPIO0

// MT3620 PIN 11 LED1
#define SAMPLE_LED_1 MT3620_GPIO8

// MT3620 PIN 12 LED2
#define SAMPLE_LED_2 MT3620_GPIO9

// MT3620 PIN 13 LED3
#define SAMPLE_LED_3 MT3620_GPIO10

// MT3620 PIN 14 SW1
#define SAMPLE_BUTTON_1 MT3620_GPIO12

// MT3620 PIN 15 SW2
#define SAMPLE_BUTTON_2 MT3620_GPIO13

// MT3620 PIN 16 SW3
#define SAMPLE_BUTTON_3 MT3620_GPIO16

// MT3620 TX PIN 18
#define SAMPLE_ISU0_UART MT3620_ISU0_UART

// MT3620 RX PIN 28
#define SAMPLE_ISU2_UART MT3620_ISU2_UART

// MT3620 PIN 29 ADC CH0
#define SAMPLE_POTENTIOMETER_ADC_CHANNEL MT3620_ADC_CHANNEL0

#define SAMPLE_POTENTIOMETER_ADC_CONTROLLER MT3620_ADC_CONTROLLER0

// PWM CONTROLLER 0 channel 0 is exposed on header 1 pin 4
#define SAMPLE_PWM_CONTROLLER0 MT3620_PWM_CONTROLLER0

// PWM CONTROLLER 1 channel 0 is exposed on header 1 pin 12
#define SAMPLE_PWM_CONTROLLER1 MT3620_PWM_CONTROLLER1

// LED PWM CONTROLLER 2 channel 0 is used by LED1 Red channel
#define SAMPLE_LED_PWM_CONTROLLER2 MT3620_PWM_CONTROLLER2

// MT3620 PIN 6 USER1
#define SAMPLE_USER_1 MT3620_GPIO1

// MT3620 PIN 7 USER2
#define SAMPLE_USER_2 MT3620_GPIO2

// MT3620 PIN 8 USER3
#define SAMPLE_USER_3 MT3620_GPIO4

// MT3620 PIN 9 USER4
#define SAMPLE_USER_4 MT3620_GPIO5

// MT3620 PIN 10 USER5
#define SAMPLE_USER_5 MT3620_GPIO6

// MT3620 PIN 17 USER6
#define SAMPLE_USER_6 MT3620_GPIO17

